# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactnativepipeline55' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativepipeline55

  

  platform :ios, '9.0'
  target 'reactnativepipeline55Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactnativepipeline55-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativepipeline55-tvOS

  target 'reactnativepipeline55-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
